### ISSUE TITLE
package "org.apache.xmlrpc" does not exist

### ISSUE THREAD

**Issue by Kevinstone-199898** [LiuYangMage/RLFluidControl#2]
Hello,thank you very much for sharing your code!
When I was running clientLilypad/clientCFD.pde in Processing, this problem occured and I have no idea how to fix it:

_No library found for org.apache.xmlrpc
Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window).
The package “org.apache.xmlrpc” does not exist. You might be missing a library._

I wish you can help me. Many thanks!

**Comment by hyperpotato** [comment]
Hi, Kevinstone-199898, 

I am one of the co-authors of the paper. The xmlrpc is in the folder clientCFD\lib\. I tested and it seems to work. Maybe if you still have questions, you may email me directly via dfan@mit.edu or dixia.fan@queensu.ca, and we may set up a zoom video chat later. 

Best

Dixia
